### ISSUE TITLE
Response log writer null pointer when migration is a repeatable

### ISSUE THREAD

**Issue by mgagp** [Geekoosh/flyway-lambda#1]
Hi, flyway has a notion of repeatable migration which do not have a version.
This causes a null pointer in 
https://github.com/Geekoosh/flyway-lambda/blob/master/src/main/java/com/geekoosh/flyway/response/Response.java

```
if(info.getApplied() != null) {
            logInfo += String.format("Applied migrations: %s, %s\n",
                    info.getApplied().length,
                    Arrays.stream(info.getApplied()).map(my -> "(" + my.getVersion().getVersion() + " [" + my.getScript() + "])")
                            .collect(Collectors.joining(", "))
            );
        }

```
my.getVersion returns null for repeatable, causing a null pointer.

**Comment by mgagp** [comment]
As of this writing, the project does not specify a licence which means
https://choosealicense.com/no-permission/
Could you specify one ?
Ideally, could it be business friendly ?
Such as https://choosealicense.com/licenses/mit/
Thanks a lot ! Great stuff

**Comment by mgagp** [comment]
I submitted a pull request to fix this issue.

**Comment by assafkamil** [comment]
Merged your pull request. Thanks for contributing

**Comment by mgagp** [comment]
Hi ! The same issue happens when there is a pending migration - My original fix was about migrations about to be applied.
I should have fixed the issue at the same time (two lines below, pfffew...)... Sending the pull request....

**Comment by Suqu13** [comment]
@assafkamil could you release a version with this fix? As far as I checked the source code of the `0.9` version, it does not contain these changes.

**Comment by assafkamil** [comment]
Done. Please check new version 0.10
