### ISSUE TITLE
Run unit tests as part of pipeline

### ISSUE THREAD

**Issue by kishaningithub** [Geekoosh/flyway-lambda#7]
I observe that the command used in test `./gradlew shadowJar` just creates the `-all.jar` and does not run unit tests.

Was there any issue in running the same using travis? I also observe that you have enabled `docker` service as part of build pipeline.

**Comment by assafkamil** [comment]
Tests are running as part of the pipeline - check https://travis-ci.org/github/Geekoosh/flyway-lambda
I had to enable to `docker` service because I'm using `testcontainers` in tests for simulating Postgres and MySQL.

**Comment by kishaningithub** [comment]
Given #10 the builds are actually not running in the travis pipeline (screenshot below)

<img width="1269" alt="Screenshot 2021-12-22 at 3 55 15 PM" src="https://user-images.githubusercontent.com/763760/147077943-38cf67e2-f2ed-42be-a6e4-6b9209fd0832.png">

**Comment by assafkamil** [comment]
Done as part of moving to github actions
